import { Project } from './types';

export const CATEGORIES = ['All', 'Visuals', 'Tools', 'Games', 'Audio'];

export const MUSIC_CONFIG = {
  url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', // Default lo-fi/chill track
  title: 'Chill Vibes',
};

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Neon Synth',
    description: 'A browser-based synthesizer with vibrant neon visuals and retro-future sounds.',
    image: 'https://picsum.photos/seed/synth/800/600',
    tags: ['Web Audio', 'Canvas', 'React'],
    category: 'Audio',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-pink-500 to-purple-600',
  },
  {
    id: '2',
    title: 'Gravity Sim',
    description: 'Interactive physics playground where you can create planets and watch them orbit.',
    image: 'https://picsum.photos/seed/gravity/800/600',
    tags: ['Physics', 'D3.js', 'Math'],
    category: 'Visuals',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-blue-500 to-cyan-400',
  },
  {
    id: '3',
    title: 'Pixel Art Editor',
    description: 'Simple yet powerful tool for creating 8-bit masterpieces right in your browser.',
    image: 'https://picsum.photos/seed/pixel/800/600',
    tags: ['Canvas', 'React', 'Local Storage'],
    category: 'Tools',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-orange-400 to-red-500',
  },
  {
    id: '4',
    title: 'Code Rain',
    description: 'Matrix-style falling code animation with customizable colors and speed.',
    image: 'https://picsum.photos/seed/matrix/800/600',
    tags: ['Animation', 'JS', 'Visuals'],
    category: 'Visuals',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-emerald-400 to-teal-600',
  },
  {
    id: '5',
    title: 'Retro Racer',
    description: 'A fast-paced pseud-3D racing game inspired by 80s arcade classics.',
    image: 'https://picsum.photos/seed/racer/800/600',
    tags: ['GameDev', 'Canvas', 'Retro'],
    category: 'Games',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-red-600 to-yellow-500',
  },
  {
    id: '6',
    title: 'Markdown Live',
    description: 'Real-time markdown editor with instant preview and export features.',
    image: 'https://picsum.photos/seed/markdown/800/600',
    tags: ['Editor', 'React', 'Utility'],
    category: 'Tools',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-indigo-500 to-blue-600',
  },
  {
    id: '7',
    title: 'Fractal Explorer',
    description: 'Dive into the infinite beauty of fractals with this interactive explorer.',
    image: 'https://picsum.photos/seed/fractal/800/600',
    tags: ['Math', 'Visuals', 'Performance'],
    category: 'Visuals',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-cyan-500 to-emerald-500',
  },
  {
    id: '8',
    title: 'Drum Machine',
    description: 'Create sick beats with this customizable 16-step drum sequencer.',
    image: 'https://picsum.photos/seed/drums/800/600',
    tags: ['Audio', 'Sequencer', 'React'],
    category: 'Audio',
    docsLink: '#',
    sourceLink: '#',
    color: 'from-purple-500 to-pink-600',
  },
];
